_target_: lightning.Trainer
max_epochs: 100
accelerator: "gpu"
default_root_dir: ${run_dir}/snapshots/${project_name}/${run_name}/
check_val_every_n_epoch: 5
accumulate_grad_batches: 1
gradient_clip_val: 1.0
callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${run_dir}/snapshots/${project_name}/${run_name}/
    auto_insert_metric_name: false
    filename: epoch_{epoch}
    save_top_k: -1
    every_n_epochs: 1
    save_last: true
  - _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: 'step'
devices: 4
strategy:
  _target_: lightning.pytorch.strategies.DDPStrategy
  find_unused_parameters: true