3:
  files:
    - /Users/maxwitte/work/crai_sr/ICON_atmo/data/next_gems/ngc4008_p1D_6.zarr
4:
  files:
    - /Users/maxwitte/work/crai_sr/ICON_atmo/data/next_gems/ngc4008_p1D_6.zarr
6:
  files:
    - /Users/maxwitte/work/crai_sr/ICON_atmo/data/next_gems/ngc4008_p1D_6.zarr