train:
  source:
    ${data_zooms}

  target:
    ${data_zooms}

  timesteps: [2,3]
  variables: ${data_variables}

val:
  source:
    ${data_zooms}

  target:
    ${data_zooms}

  timesteps: [10]
  variables: ${data_variables}

test:
  source:
    ${data_zooms}

  target:
    ${data_zooms}
    
  timesteps: [10]
  variables: ${data_variables}