_target_: latengen.model.pl_diffusion.LightningDiffusionGenerator
lr: 1e-4
lr_warmup: 5000
model:
  _target_: latengen.model.diffusion.model.DiffusionGenerator
  model_channels: 64
  layer_depth: 2
  seq_length: ${data.dataset.seq_length}
  block_type: "transformer"
  updown: "resnet"
  conv_factors: [1, 1, 1]
  img_sizes: [6, 12]
  patch_emb_size: [1, 1, 1]
  out_channels: 4
  conditioning: null
gaussian_diffusion:
  _target_: latengen.model.diffusion.respace.SpacedDiffusion
  diffusion_steps: 1000
  diffusion_step_scheduler: "cosine"
