_target_: stableclimgen.src.models.diffusion.pl_diffusion.LightningDiffusionGenerator
lr: 1e-4
lr_warmup: 5000
model:
  _target_: stableclimgen.src.models.diffusion.model.DiffusionGenerator
  model_channels: 64
  layer_depth: 2
  seq_length: ${dataloader.dataset.seq_length}
  block_type: "transformer"
  updown: "resnet"
  conv_factors: [1, 2, 2, 4]
  bottleneck: true
  bottleneck_spat_att: true
  bottleneck_temp_att: false
  img_sizes: [96, 192]
  patch_emb_size: [1, 3, 3]
  patch_emb_kernel: [1, 3, 3]
  out_channels: 1
  conditioning: "channel"
gaussian_diffusion:
  _target_: stableclimgen.src.models.diffusion.respace.SpacedDiffusion
  diffusion_steps: 1000
  diffusion_step_scheduler: "cosine"
