_target_: stableclimgen.src.models.diffusion.pl_diffusion.LightningDiffusionGenerator
lr: 1e-4
lr_warmup: 5000
model:
  _target_: stableclimgen.src.models.diffusion.model.DiffusionGenerator
  model_channels: 64
  n_heads: 4
  layer_depth: 2
  seq_length: ${dataloader.dataset.seq_length}
  block_type: "transformer"
  updown: null
  conv_factors: [1, 1, 1]
  disable_temp_attention: true
  img_sizes: [96, 192]
  patch_emb_size: [1, 3, 3]
  patch_emb_kernel: [1, 3, 3]
  out_channels: 1
  conditioning: null
  rel_position: "bias"
gaussian_diffusion:
  _target_: stableclimgen.src.models.diffusion.respace.SpacedDiffusion
  diffusion_steps: 1000
  diffusion_step_scheduler: "cosine"
