_target_: stableclimgen.src.models.mgno_transformer.pl_mgno_diffusion_model.Lightning_MGNO_diffusion_transformer
lambda_loss_dict:
  MSE_loss: 1
  NH_loss: 0.0
  Grad_loss: 0
noise_std: 0
lr_groups:
  - param_group: 'params'
    lr: 2e-4
    lr_warmup: 500
  - param_group: 'no_params'
    lr: 1e-4
    lr_warmup: 500
  - param_group: 'attention'
    lr: 2e-4
    lr_warmup: 500
interpolator_settings:
  search_level: 3
  nh_inter: 3
  power: 1
model:
  _target_: stableclimgen.src.models.mgno_transformer.mgno_transformer_mg.MGNO_Transformer_MG
  mgrids: ${mgrids}
  input_dim: 2
  lifting_dim: 8
  output_dim: 1
  n_vars_total: 3
  n_head_channels: 32
  rotate_coord_system: true
  p_dropout: 0
  block_type: 'pre_layer_norm'
  with_gamma: true
  omit_backtransform: true
  rank: 0.5
  rank_cross: 0.5
  layer_type: 'CrossTucker'
  input_embed_names: ["DensityEmbedder", "CoordinateEmbedder"]
  input_embed_confs: ${embedding}
  block_configs:
    - _target_: stableclimgen.src.models.mgno_transformer.mgno_block_confs.MGStackedEncoderDecoderConfig
      global_levels_output: [0,2,4]
      global_levels_no: 4
      model_dims_out: [16,8,8]
      concat_layer_type: 'CrossTucker'
      reduction_layer_type: 'CrossTucker'
      embed_names: ["CoordinateEmbedder", "DiffusionStepEmbedder"]
      embed_confs: ${embedding}
      no_layer_settings:
        no_layer_type: 'VonMises'
        n_params: [3]
        nh_in_encode: false
        nh_in_decode: true
        global_params_learnable: [false, false]
        sigma: 1e-3
        kappa: 8.0
    - _target_: stableclimgen.src.models.mgno_transformer.mgno_block_confs.MGEncoderDecoderConfig
      mg_reduction: 'linear'
      global_levels_output: [0,2,4]
      global_levels_no: [0,2,4]
      model_dims_out: [16,16,16]
      rule: "="
      embed_names: ["CoordinateEmbedder", "DiffusionStepEmbedder"]
      embed_confs: ${embedding}
      no_layer_settings:
        no_layer_type: 'VonMises'
        n_params: [3]
        nh_in_encode: true
        nh_in_decode: false
        global_params_learnable: [false, false]
        sigma: 1e-3
        kappa: 8.0
    - _target_: stableclimgen.src.models.mgno_transformer.mgno_block_confs.MGProcessingConfig
      model_dims_out: [[16,16],[16,16],[16,16]]
      layer_settings_levels:
        - type: "spatial_att"
          n_head_channels: 4
          embed_confs: ${embedding}
          embedder_names: [["CoordinateEmbedder", "DiffusionStepEmbedder"],["TimeEmbedder", "DiffusionStepEmbedder"],["CoordinateEmbedder","TimeEmbedder", "DiffusionStepEmbedder"]]
          spatial_attention_configs:
            nh: false
            seq_lvl: 3
            timesteps: ${dataloader.dataset.n_sample_timesteps}
            blocks: ["s", "t", "mlp"]
        - type: "spatial_att"
          n_head_channels: 4
          embed_confs: ${embedding}
          embedder_names: [["CoordinateEmbedder", "DiffusionStepEmbedder"],["TimeEmbedder", "DiffusionStepEmbedder"],["CoordinateEmbedder","TimeEmbedder", "DiffusionStepEmbedder"]]
          spatial_attention_configs:
            nh: false
            seq_lvl: 3
            timesteps: ${dataloader.dataset.n_sample_timesteps}
            blocks: ["s", "t", "mlp"]
    - _target_: stableclimgen.src.models.mgno_transformer.mgno_block_confs.MGStackedEncoderDecoderConfig
      global_levels_output: [0,2,4]
      global_levels_no: 4
      model_dims_out: [16,8,8]
      concat_layer_type: 'CrossTucker'
      reduction_layer_type: 'CrossTucker'
      embed_names: ["CoordinateEmbedder", "DiffusionStepEmbedder"]
      embed_confs: ${embedding}
      no_layer_settings:
        no_layer_type: 'VonMises'
        n_params: [3]
        nh_in_encode: false
        nh_in_decode: false
        global_params_learnable: [false, false]
        sigma: 1e-3
        kappa: 8.0
    - _target_: stableclimgen.src.models.mgno_transformer.mgno_block_confs.MGStackedEncoderDecoderConfig
      global_levels_output: [0]
      global_levels_no: 4
      model_dims_out: [16,8,8]
      no_level_step: 2
      concat_layer_type: 'CrossTucker'
      reduction_layer_type: 'CrossTucker'
      embed_names: ["CoordinateEmbedder", "DiffusionStepEmbedder"]
      embed_confs: ${embedding}
      no_layer_settings:
        no_layer_type: 'VonMises'
        n_params: [3]
        nh_in_encode: false
        nh_in_decode: false
        global_params_learnable: [false, false]
        sigma: 1e-3
        kappa: 8.0

gaussian_diffusion:
  _target_: stableclimgen.src.models.diffusion.respace.SpacedDiffusion
  diffusion_steps: 1000
  diffusion_step_scheduler: "cosine"