_target_: stableclimgen.src.models.vae.pl_vae.LightningVAE
lr: 1e-4
lr_warmup: 5000
model:
  _target_: stableclimgen.src.models.vae.model.VAE
  init_in_ch: 1
  final_out_ch: 1
  model_channels: 64
  patch_emb_size: [1, 1]
  patch_emb_kernel: [3, 3]
  block_configs:
    - _target_: stableclimgen.src.models.vae.model.VAEBlockConfig
      block_type: "resnet"
      depth: 1
      enc: true
      ch_mult: [1, 1, 1, 2, 2, 2, 2, 2, 2, 4, 4]
      sub_confs:
        blocks: [ "id", "id", "down", "id", "id", "down", "id", "id", "down", "id", "id" ]
    - _target_: stableclimgen.src.models.vae.model.VAEBlockConfig
      block_type: "resnet"
      depth: 1
      dec: true
      ch_mult: [ 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1 ]
      sub_confs:
        blocks: [ "id", "id", "id", "up", "id", "id", "id", "up", "id", "id", "id", "up", "id", "id", "id" ]
  quant_config:
    _target_: stableclimgen.src.models.vae.model.QuantConfig
    block_type: "conv"
    latent_ch: [4, 4]
    sub_confs:
      blocks: ["id", "id"]
      kernel_size: [1, 1]