3:
  files:
    - /home/joe/PycharmProjects/climategen/data/zarr/ngc4008_P1D_6.zarr
5:
  files:
    - /home/joe/PycharmProjects/climategen/data/zarr/ngc4008_P1D_6.zarr
6:
  files:
    - /home/joe/PycharmProjects/climategen/data/zarr/ngc4008_P1D_6.zarr
