dataset:
  _target_: stableclimgen.src.data.datasets_regular.MaskClimateDataset
  norm_dict: ${run_dir}/input/norm_dict.json
  n_sample_timesteps: 1
  p_dropout: 0.99
  p_drop_vars: 0
  p_drop_timesteps: 0

datamodule:
  _target_: stableclimgen.src.data.pl_data_module.DataModule
  batch_size: 1
  num_workers: 1
  use_costum_ddp_sampler: false