dataset:
  _target_: latengen.utils.dataloader.NetCDFLoader
  data_dir_dict: ../../input/data_netcdf.json
  seq_length: 1
  mask_mode: "random"
  normalization: "img"
  norm_quantile: 0.95
  strict: true

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  num_workers: 12