dataset:
  _target_: stableclimgen.src.utils.datasets_icon.NetCDFLoader_lazy
  data_dict: /Users/maxwitte/work/crai_sr/ICON_atmo/data.json
  norm_dict: /Users/maxwitte/work/crai_sr/ICON_atmo/norm_dict.json
  grid_processing: ${mgrids.grid_file}
  coarsen_sample_level: 6
  search_radius: 2
  nh_input: 1
  sample_for_norm: 2
  lazy_load: true
  p_dropout: 1
  random_p: false
  skewness_exp: 3
  p_drop_vars: 1
  n_drop_vars: 1
  n_sample_vars: 3


datamodule:
  _target_: stableclimgen.src.utils.pl_data_module.DataModule
  batch_size: 2
  num_workers: 4
  use_costum_ddp_sampler: false