dataset:
  _target_: stableclimgen.src.utils.datasets_regular.MaskClimateDataset
  data_dict: ../../input/data_netcdf.json
  norm_dict: ../../input/norm_dict.json
  seq_length: 1

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 4
  num_workers: 12