dataset:
  _target_: stableclimgen.src.utils.datasets_healpix.HealPixLoader
  data_dict: ${run_dir}/input/data_healpix.json
  zoom_patch_sample: 2
  norm_dict: ${run_dir}/input/norm_dict.json
  p_dropout: 0.95
  p_drop_vars: 1
  n_sample_timesteps: 1

datamodule:
  _target_: stableclimgen.src.utils.pl_data_module.DataModule
  batch_size: 2
  num_workers: 1
  use_costum_ddp_sampler: false