dataset:
  _target_: stableclimgen.src.data.datasets_healpix.HealPixLoader
  norm_dict: ${run_dir}/input/norm_dict.json
  p_dropout: 0
  random_p: false
  p_dropout_all: 1
  n_sample_variables: -1
  output_binary_mask: true
  apply_diff: true
  mask_ts_mode: 'repeat'
  sampling_zooms:
    3:
      n_past_ts: 2
      n_future_ts: 2
      zoom_patch_sample: -1
      mask_last_ts: true
    5:
      n_past_ts: 1
      n_future_ts: 1
      zoom_patch_sample: -1
      mask_last_ts: true
    6:
      n_past_ts: 1
      n_future_ts: 0
      zoom_patch_sample: -1
      mask_last_ts: true
  output_max_zoom_only: false
datamodule:
  _target_: stableclimgen.src.data.pl_data_module.DataModule
  batch_size: 2
  num_workers: 0
  use_costum_ddp_sampler: false