dataset:
  _target_: stableclimgen.src.utils.datasets_healpix.HealPixLoader
  norm_dict: ${run_dir}/input/norm_dict.json
  p_dropout: 0.7
  n_sample_groups: -1
  output_binary_mask: false
  sampling_zooms:
    3:
      n_past_ts: 2
      n_future_ts: 0
      zoom_patch_sample: -1
    4:
      n_past_ts: 0
      n_future_ts: 0
      zoom_patch_sample: -1
    6:
      n_past_ts: 0
      n_future_ts: 0
      zoom_patch_sample: 0
  dropout_zooms:
    3:
      p_dropout: 0.5
      p_drop_full: 0
    4:
      p_dropout: 0.5
      p_drop_full: 0
    5:
      p_dropout: 0.5
      p_drop_full: 0
  n_sample_vars: 2
  output_binary_mask: true

datamodule:
  _target_: stableclimgen.src.utils.pl_data_module.DataModule
  batch_size: 1
  num_workers: 0
  use_costum_ddp_sampler: false