CoordinateEmbedder:
  in_channels: 2
  embed_dim: 64
  shared: false
DiffusionStepEmbedder:
  in_channels: 64
  embed_dim: 64
  shared: true
VariableEmbedder:
  in_channels: 16
  embed_dim: 64
  shared: false
GridEmbedder:
  in_channels: 11
  embed_dim: 64
  shared: true
MaskEmbedder:
  in_channels: 2
  embed_dim: 64