CoordinateEmbedder:
  in_channels: 2
  embed_dim: 64
  shared: false
DensityEmbedder:
  in_channels: 1
  embed_dim: 64
  shared: false
UncertaintyEmbedder:
  in_channels: 1
  embed_dim: 64
  in_channels_var: ${embedding.GroupEmbedder.in_channels}
  shared: false
DiffusionStepEmbedder:
  in_channels: 64
  embed_dim: 64
  shared: false
GroupEmbedder:
  in_channels: 16
  embed_dim: 64
  shared: false
GridEmbedder:
  in_channels: 11
  embed_dim: 64
  shared: false
MaskEmbedder:
  in_channels: 2
  embed_dim: 64
TimeEmbedder:
  in_channels: 1
  embed_dim: 64
  time_scales: [1, 7, 30.4375, 365.25]
  time_min: 1577923200
  time_max: 2524608000
MGEmbedder:
  shared: false
  in_channels: 3
  embed_dim: 64
  mg_emb_confs:
    zoom: 6
    features: 64
    n_groups: 2
    init_method: random
  layer_confs:
    rank_channel: 0
    n_groups: 3
    bias: true

