CoordinateEmbedder:
  in_channels: 2
  embed_dim: 64
  shared: false
DiffusionStepEmbedder:
  in_channels: 64
  embed_dim: 64
  shared: true
VariableEmbedder:
  in_channels: 3
  embed_dim: 64
  shared: false
GridEmbedder:
  in_channels: 5
  embed_dim: 64
  shared: false