_target_: stableclimgen.src.utils.logger.CustomImageLogger
logger_type: wandb
save_snapshot_images: true
log_snapshot_images: false
save_dir: ${run_dir}/logs/${project_name}/${run_name}/
project: ${project_name}
name: ${run_name}