defaults:
  - trainer: trainer
  - logger: wandb
  - model: diffusion_transformer
  - dataloader: xarray
  - hydra: default
  - embedding: default
  - _self_

ckpt_path: null

run_name: diffusion
run_dir: ../..
