defaults:
  - trainer: trainer
  - logger: wandb
  - model: diffusion_cnn
  - dataloader: netcdf_regular
  - hydra: default
  - embedding: default
  - _self_

ckpt_path: null

project_name: diffusion
run_name: default
run_dir: ../..
