defaults:
  - trainer: icon_transformer
  - logger: wandb
  - model: healpix_transformer
  - dataloader: zarr
  - hydra: default
  - _self_

ckpt_path: null

run_name: healpix_transformer
run_dir: ../..
