defaults:
  - model: mgno_vae
  - mgrids: healpix
  - trainer: mgno_transformer
  - embedding: default
  - dataloader: zarr_healpix
  - hydra: default
  - _self_

ckpt_path: ../../snapshots/${project_name}/${run_name}/last.ckpt
output_path: ../../evaluations/${project_name}/${run_name}/sample.pt

project_name: healpix_vae
run_name: default
run_dir: ../..