defaults:
  - trainer: mgno_transformer
  - logger: wandb
  - model: mgno_transformer
  - mgrids: healpix
  - embedding: default
  - dataloader: zarr_healpix
  - hydra: default
  - _self_

ckpt_path: null

run_name: healpix_transformer
config_name: default
run_dir: ../..
