defaults:
  - trainer: mgno_transformer
  - logger: wandb
  - model: mgno_vae
  - mgrids: healpix
  - dataloader: zarr_healpix
  - hydra: default
  - embedding: default
  - _self_

ckpt_path: null

run_name: healpix_vae
run_dir: ../..
