defaults:
  - trainer: mgno_transformer
  - logger: wandb
  - model: mg_vae
  - mgrids: healpix
  - dataloader: zarr_healpix
  - hydra: default
  - embedding: default
  - _self_

ckpt_path: null

project_name: mg_vae
run_name: default
run_dir: ../..
