defaults:
  - model: mgno_transformer
  - mgrids: icon
  - embedding: default
  - dataloader: netcdf_mgno
  - hydra: default
  - _self_

ckpt_path: '/Users/maxwitte/work/climgen_out/snapshots/mgno_transformer/last.ckpt'
output_dir: '/Users/maxwitte/work/climgen_out/outputs'

run_name: mgno_transformer
run_dir: ../..
