defaults:
  - trainer: mgno_transformer
  - logger: wandb
  - model: mgno_transformer_mg
  - mgrids: healpix
  - dataloader: zarr_healpix
  - embedding: default
  - hydra: default
  - _self_

ckpt_path: null

run_name: mgno_transformer
config_name: default
project_name: test
run_dir: ../..
