defaults:
  - trainer: mgno_transformer
  - logger: wandb
  - model: mgno_transformer_mg_orig
  - mgrids: icon
  - dataloader: netcdf_mgno
  - embedding: default
  - hydra: default
  - _self_

ckpt_path: null

run_name: mgno_transformer
config_name: default
project_name: test
run_dir: /Users/maxwitte/work/climgen_out
