defaults:
  - trainer: mgno_transformer
  - logger: wandb
  - model: time_transformer
  - mgrids: healpix
  - dataloader: zarr_healpix
  - hydra: default
  - embedding: default
  - _self_

ckpt_path: null

project_name: mgno_diffusion_transformer
run_name: default
run_dir: ../..
